### ISSUE TITLE
Add-on won't compile in debian

### ISSUE THREAD

**Issue by hudokkow** [kodi-pvr/pvr.mythtv#10]
@janbar please see what's going on with your add-on. It won't compile on debian using debuild but I can't reproduce the error in my machine.
Build log is available at https://launchpadlibrarian.net/206802274/buildlog_ubuntu-vivid-amd64.kodi-pvr-mythtv_2.1.1-2~vivid_BUILDING.txt.gz

The only obvious thing is -DUSE_LTO=1 missing from debian/rules but adding it breaks build.

**Comment by wsnipex** [comment]
if LTO breaks the build, just remove it from debian packaging

**Comment by hudokkow** [comment]
Already removed. See https://github.com/kodi-pvr/pvr.mythtv/blob/master/debian/rules#L16
It builds fine with cmake and debuild but if I add it back it breaks debuild.

**Comment by janbar** [comment]
My master (2.1.0) build well in my launchpad account. Seems last commits in debian files have broken something here. I haven't yet merged last changes from here to my repos.

**Comment by hudokkow** [comment]
Thanks, appreciate your help.

It can only be the introduction of libplatform - https://github.com/kodi-pvr/pvr.mythtv/commit/285f4b7ebbd5c2576bba1e35bb6b82938b5530cb - or multi-arch packaging https://github.com/kodi-pvr/pvr.mythtv/commit/626e6d2b1158f00cedfe1fedaf4d225b2e649903

Nothing else changed but like I said above, I can't reproduce the exact error on my machine and that makes it hard to find the culprit.

> -- Install configuration: "Release"
> -- Installing: /build/buildd/kodi-pvr-mythtv-2.1.1/debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.mythtv/pvr.mythtv.so.2.1.1
> -- Installing: /build/buildd/kodi-pvr-mythtv-2.1.1/debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.mythtv/pvr.mythtv.so.15.0
> -- Installing: /build/buildd/kodi-pvr-mythtv-2.1.1/debian/tmp/usr/lib/x86_64-linux-gnu/kodi/addons/pvr.mythtv/pvr.mythtv.so
> ...
> ...
> ...
> dh_install
> /build/buildd/kodi-pvr-mythtv-2.1.1/debian/kodi-pvr-mythtv.install: 1: /build/buildd/kodi-pvr-mythtv-2.1.1/debian/kodi-pvr-mythtv.install: usr/lib/_/kodi/addons/pvr.mythtv/pvr.mythtv.so_: not found
> /build/buildd/kodi-pvr-mythtv-2.1.1/debian/kodi-pvr-mythtv.install: 2: /build/buildd/kodi-pvr-mythtv-2.1.1/debian/kodi-pvr-mythtv.install: usr/share/kodi/addons/pvr.mythtv: not found
> dh_install: problem reading debian/kodi-pvr-mythtv.install: 
> debian/rules:13: recipe for target 'binary' failed
> make: **\* [binary] Error 127
> dpkg-buildpackage: error: /usr/bin/fakeroot debian/rules binary gave error exit status 2

It doesn't find pvr.mythtv.so\* but files are there and I confirmed they exist on my deb package.

**Comment by janbar** [comment]
@hudokkow , please could you give me the account name or link of launchpad you used to build. I will try to build it with copy of your recipe. Thanks.

**Comment by hudokkow** [comment]
I assume this is what you mean: https://launchpad.net/~wsnipex/+archive/ubuntu/kodi-git

**Comment by wsnipex** [comment]
The error above must be from before https://github.com/kodi-pvr/pvr.mythtv/commit/6fb769da0897de3829bcc4e5a3810c8c9fdef34a
I've just rebuilt it: https://launchpad.net/~wsnipex/+archive/ubuntu/kodi-git/+packages?field.name_filter=mythtv&field.status_filter=published&field.series_filter=

all good.
