### ISSUE TITLE
Addon no longer works for mythtv versions > 0.28

### ISSUE THREAD

**Issue by develroo** [kodi-pvr/pvr.mythtv#110]
Although channel and programme schedules work trying to stream live or recorded tv does not. You simple get a Channel Unavailable loop. 

The current stable version of Mythtv is 0.30

**Comment by janbar** [comment]
This repository isn't live. Please go to the PVR Mythtv section of the Kodi forum , where you will find the answer to resolve your issue. Else the live repository is https://github.com/janbar/pvr.mythtv .
